spring.application.name=demo

spring.ai.openai.chat.options.model =nex-agi/nex-n2.5-pro:free

spring.ai.openai.base-url = https://openrouter.ai/api/v1


spring.ai.openai.api-key = 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